version: "1.0"
networks:
  shop-network:
    driver: bridge
volumes:
  client-volume:
services:
  client:
    build: ./client
    volumes:
      - client-volume:/usr/src/client/dist
    networks:
      - shop-network
  server:
    build: ./server
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_DB=$PG_DB
      - POSTGRES_PORT=$PG_PORT
      - WAIT_HOSTS=postgres:$PG_PORT
    networks:
      - shop-network
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    volumes:
      - client-volume:/usr/share/nginx/html
    depends_on:
      - client
      - server
    networks:
      - shop-network
    ports:
      - 80:80
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_DB=$PG_DB
      - POSTGRES_PORT=$PG_PORT
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - shop-network